apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ok2x7lh5l-go
  janus-idp.io/tekton: ok2x7lh5l-go
  backstage.io/kubernetes-id: ok2x7lh5l-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ok2x7lh5l-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
